### ISSUE TITLE
Action ignores actionlint.yml config

### ISSUE THREAD

**Issue by piotrekkr** [devops-actions/actionlint#63]
Hello. I've noticed today that this action does not care about my configuration in `.github/actionlint.yml`. 
I'm using this action as follows:
```yaml
jobs:
  check:
    name: Actionlint Check
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - name: Run Actionlint
        uses: devops-actions/actionlint@v0.1.3
        with:
          shellcheck_opts: ${{ vars.ACTIONLINT_SHELLCHECK_OPTS }}
```
Ant this always return errors even when I ignored those using `actionlint.yml` file. Was quite surprised since locally testing my code with `rhysd/actionlint:latest` image gives errors when there is no `.github/actionlint.yml`:

```
$ docker run --rm -v $(pwd):/repo -e SHELLCHECK_OPTS="-e SC2129" --workdir /repo rhysd/actionlint:latest -color
.github/workflows/create-qa-env.yml:190:11: input "build_env" is not defined in action "Build API" defined at "./.github/actions/build". available inputs are "app_version", "image_tags", "load_images", "push_images", "src_dir", "target" [action]
    |
190 |           build_env: qa
    |           ^~~~~~~~~~
.github/workflows/create-qa-env.yml:192:11: input "api_url" is not defined in action "Build API" defined at "./.github/actions/build". available inputs are "app_version", "image_tags", "load_images", "push_images", "src_dir", "target" [action]
    |
192 |           api_url: https://api-${{ needs.init.outputs.qa_id }}.xxxxxxx.com
    |           ^~~~~~~~
```
and all is good when I ignore those in `.github/actionlint.yml`:
```yaml
paths:
  .github/workflows/create-qa-env.yml:
    ignore:
      - 'input "build_env" is not defined in action .+'
      - 'input "api_url" is not defined in action .+'
```
and run again:
```
$ docker run --rm -v $(pwd):/repo -e SHELLCHECK_OPTS="-e SC2129" --workdir /repo rhysd/actionlint:latest -color

```

To test this further I've changed my usage to this:

```yaml
jobs:
  check:
    name: Actionlint Check
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false

      - name: Run Actionlint
        env:
          SHELLCHECK_OPTS: ${{ vars.ACTIONLINT_SHELLCHECK_OPTS }}
        run: |
          docker run \
            -v $GITHUB_WORKSPACE:/repo \
            --workdir /repo \
            -e SHELLCHECK_OPTS \
            rhysd/actionlint:1.7.7@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9
```
Now it shows error where there is no `.github/actionlint.yml` file and do not report errors when I add this file and ignore them.

Maybe it is because of outdated actionlint docker image? There is 1.7.7 version available that works just fine for me. Can you take a look at this? Thank you.
